//templates compositores
exports.compositoresListPage = (slist,d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="icon" href="favicon.png"/>
        <link rel ="stylesheet" href="w3.css"/>
        <title>Compositores</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-teal">
                <h1>Lista de compositores
                <a class ="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                </h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Periodo</th>
                        <th>Ações</th>
                    </tr>`
    for(let i = 0; i < slist.length; i++){
        pagHTML += `
                    <tr>
                        <td>${slist[i].id}</td>
                        <td>
                            <a href="/compositores/${slist[i].id}">
                                ${slist[i].nome}
                        </td>
                        <td>${slist[i].periodo}</td>
                        <td>
                            [<a class="w3-btn w3-round w3-teal" href="/compositores/edit/${slist[i].id}">Edit</a>]
                            [<a class="w3-btn w3-round w3-red" href="/compositores/delete/${slist[i].id}">Delete</a>]
                        </td>
                    </tr>`
    }
        pagHTML += `            
                </table>   
            </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}


exports.compositorPage = (slist,d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="icon" href="favicon.png"/>
        <link rel ="stylesheet" href="w3.css"/>
        <title>${slist.nome}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-teal">
                <h1>${slist.nome}
                </h1>
            </header>
            <div class="w3-container">
                <ul>
                        <li>Biografia: ${slist.bio}</li>
                        <li>Data nascimento: ${slist.dataNasc}</li>
                        <li>Data óbito: ${slist.dataObito}</li>
                        <li>Período: ${slist.periodo}</li>         
                </ul>   
            </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}

exports.compositorFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                    </fieldset>

                    <fieldset>
                        <legend>Período</legend>
                        <input class="w3-check" type="checkbox" name="periodo" value="Barroco"/>
                        <label>Barroco</label>
                        <input class="w3-check" type="checkbox" name="periodo" value="Renascimento"/>
                        <label>Renascimento</label>
                    </fieldset> 
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function(c, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>${c.nome}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="text" name="dataNasc" value="${c.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="text" name="dataObito" value="${c.dataObito}"/>
                        <fieldset>
                        <legend>Período</legend>
                        <input class="w3-check" type="checkbox" name="periodo" value="Barroco"/>
                        <label>Barroco</label>
                        <input class="w3-check" type="checkbox" name="periodo" value="Renascimento"/>
                        <label>Renascimento</label>
                        </fieldset>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${c.bio}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Submit Changes</button>
                </form>
                <br/>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}





// templates periodos
exports.periodosListPage = (slist, d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
        <title>Períodos</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Lista de períodos
                <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                </h1>
            </header>
            <div class="w3-container">
                <table class="w3-table-all">
                    <tr>
                        <th>ID</th>
                        <th>Periodo</th>
                        <th>Ações</th>
                    </tr>`;
    for (let i = 0; i < slist.length; i++) {
        pagHTML += `
                    <tr>
                        <td>${slist[i].id}</td>
                        <td> <a href="/periodos/${slist[i].id}">
                                ${slist[i].periodo}</td>
                        <td>
                            [<a class="w3-btn w3-round w3-teal" href="/periodos/edit/${slist[i].id}">Edit</a>]
                            [<a class="w3-btn w3-round w3-red" href="/periodos/delete/${slist[i].id}">Delete</a>]
                        </td>
                    </tr>`;
    }
    pagHTML += `            
                </table>   
            </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `;
    return pagHTML;
};


exports.periodosPage = (slist,d) => {
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel ="icon" href="favicon.png"/>
        <link rel ="stylesheet" href="w3.css"/>
        <title>${slist.periodo}</title>
    </head>
    <body>
        <div class="w3-card-4">
            <header class = "w3-container w3-teal">
                <h1>${slist.periodo}
                </h1>
            </header>
            <div class="w3-container">
                <ul>
                        <li><b>Periodo:</b> ${slist.periodo}</li>
                        <li><b>Compositores:</b> ${slist.compositores}</li>       
                </ul>   
            </div>
        <footer class="w3-container w3-blue">
            <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
        </footer>
        </div>


    </body>
    </html>
    `
    return pagHTML
}


exports.periodosFormPage = function(d){
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Período Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Período Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                        <label>Compositores</label>
                        <input class="w3-input w3-round" type="text" name="compositores"/>
                    </fieldset>

                    
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.periodosFormEditPage = function(p, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>${p.periodo}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Período Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Período</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                        <label>Compositores</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${p.compositores}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-red w3-mb-2" type="submit">Submit Changes</button>
                </form>
                <br/>
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2023 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}


